export class Match {
  id: string = '';
  status: string | undefined;
  tournament: string | undefined;
  round: string | undefined;
  order: string | undefined;
  tableNum: number | undefined;
  playerAid: string | undefined;
  playerAname: string | undefined;
  playerAduplicated: boolean = false;
  playerAtable: number | undefined;
  playerAscore: number = 0;
  playerBid: string | undefined;
  playerBname: string | undefined;
  playerBscore: number = 0;
  playerBduplicated: boolean = false;
  playerBtable: number | undefined;
  startTime: Date | undefined;
  finishedTime: Date | undefined;
}
