import {HttpClientModule} from '@angular/common/http';
import {NgModule} from '@angular/core';
import {ReactiveFormsModule} from '@angular/forms';
import {MatButtonModule} from '@angular/material/button';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatIconModule} from '@angular/material/icon';
import {MatInputModule} from '@angular/material/input';
import {BrowserModule} from '@angular/platform-browser';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {IntegrationService} from 'src/app/integration/integration-service';
import {TournamentService} from 'src/app/tournament/tournament.service';
import {AppRoutingModule} from './app-routing.module';
import {AppComponent} from './app.component';
import {MatchComponent} from './match/match.component';
import {TableComponent} from './table/table.component';
import {TournamentComponent} from './tournament/tournament.component';

@NgModule({
  declarations: [
    AppComponent,
    TournamentComponent,
    TableComponent,
    MatchComponent
  ],
  imports: [
    /**
     * Generated by cli
     */
    AppRoutingModule,

    /**
     * Angular modules
     */
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    ReactiveFormsModule,

    /**
     * Material modules
     */
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
  ],
  providers: [
    IntegrationService,
    TournamentService
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
